"""Builtin function definitions."""

from __future__ import annotations

from dataclasses import dataclass

from p2w.wat.builtins import (
    ABS_CODE,
    ALL_CODE,
    ANY_CODE,
    ASCII_CODE,
    BIN_CODE,
    BOOL_CODE,
    BYTES_CODE,
    CALLABLE_CODE,
    CHR_CODE,
    DELATTR_CODE,
    DICT_CODE,
    DIVMOD_CODE,
    ENUMERATE_CODE,
    FILTER_CODE,
    FLOAT_CODE,
    GETATTR_CODE,
    HASATTR_CODE,
    HEX_CODE,
    ID_CODE,
    INT_CODE,
    ISINSTANCE_CODE,
    ISSUBCLASS_CODE,
    JS_ALERT_CODE,
    JS_GET_ELEMENT_CODE,
    JS_LOG_CODE,
    JS_SET_TEXT_CODE,
    LEN_CODE,
    LIST_CODE,
    MAP_CODE,
    MAX_CODE,
    MIN_CODE,
    NEXT_CODE,
    OCT_CODE,
    ORD_CODE,
    POW_CODE,
    PRINT_CODE,
    RANGE_BUILTIN_CODE,
    REPR_CODE,
    REVERSED_CODE,
    ROUND_CODE,
    SET_CODE,
    SETATTR_CODE,
    SORTED_CODE,
    STR_CODE,
    SUM_CODE,
    SUPER_CODE,
    TUPLE_CODE,
    TYPE_CODE,
    ZIP_CODE,
)


@dataclass
class BuiltinFunc:
    """A builtin function with its WAT implementation."""

    name: str
    code: str


BUILTINS = [
    BuiltinFunc("print", PRINT_CODE),
    BuiltinFunc("len", LEN_CODE),
    BuiltinFunc("min", MIN_CODE),
    BuiltinFunc("max", MAX_CODE),
    BuiltinFunc("abs", ABS_CODE),
    BuiltinFunc("sum", SUM_CODE),
    BuiltinFunc("int", INT_CODE),
    BuiltinFunc("bool", BOOL_CODE),
    BuiltinFunc("str", STR_CODE),
    BuiltinFunc("chr", CHR_CODE),
    BuiltinFunc("ord", ORD_CODE),
    BuiltinFunc("float", FLOAT_CODE),
    BuiltinFunc("repr", REPR_CODE),
    BuiltinFunc("list", LIST_CODE),
    BuiltinFunc("range", RANGE_BUILTIN_CODE),
    BuiltinFunc("map", MAP_CODE),
    BuiltinFunc("filter", FILTER_CODE),
    BuiltinFunc("sorted", SORTED_CODE),
    BuiltinFunc("dict", DICT_CODE),
    BuiltinFunc("tuple", TUPLE_CODE),
    BuiltinFunc("set", SET_CODE),
    BuiltinFunc("enumerate", ENUMERATE_CODE),
    BuiltinFunc("zip", ZIP_CODE),
    BuiltinFunc("any", ANY_CODE),
    BuiltinFunc("all", ALL_CODE),
    BuiltinFunc("round", ROUND_CODE),
    BuiltinFunc("isinstance", ISINSTANCE_CODE),
    BuiltinFunc("issubclass", ISSUBCLASS_CODE),
    BuiltinFunc("super", SUPER_CODE),
    BuiltinFunc("callable", CALLABLE_CODE),
    BuiltinFunc("bytes", BYTES_CODE),
    BuiltinFunc("hasattr", HASATTR_CODE),
    BuiltinFunc("getattr", GETATTR_CODE),
    BuiltinFunc("setattr", SETATTR_CODE),
    BuiltinFunc("delattr", DELATTR_CODE),
    BuiltinFunc("type", TYPE_CODE),
    BuiltinFunc("pow", POW_CODE),
    BuiltinFunc("divmod", DIVMOD_CODE),
    BuiltinFunc("hex", HEX_CODE),
    BuiltinFunc("bin", BIN_CODE),
    BuiltinFunc("oct", OCT_CODE),
    BuiltinFunc("reversed", REVERSED_CODE),
    BuiltinFunc("next", NEXT_CODE),
    BuiltinFunc("ascii", ASCII_CODE),
    BuiltinFunc("id", ID_CODE),
    # JavaScript interop builtins (for browser environment)
    BuiltinFunc("js_log", JS_LOG_CODE),
    BuiltinFunc("js_alert", JS_ALERT_CODE),
    BuiltinFunc("js_get_element", JS_GET_ELEMENT_CODE),
    BuiltinFunc("js_set_text", JS_SET_TEXT_CODE),
]
